bar_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from bar_inventory.forms import UserLoginForm
from bar_inventory.models import User, db
from werkzeug.security import check_password_hash

from flask_login import login_user, logout_user, current_user, login_required 

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
     
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            print(email, username)

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have succesfully created a user account {username}', 'user-created')

            return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please check your form') 
    return render_template('signup.html', form = form )

    

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try: 
        if request.method == 'POST' and form.validate_on_submit(): 
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                print(f"this is the logged user {logged_user}")
                login_user(logged_user)
                flash(f"You were successfully logged in: Via email/password", 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
        
    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')
    return render_template('signin.html', form = form)

bar_inventory/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from bar_inventory.forms import BarForm
from bar_inventory.models import Bar, db
from bar_inventory.helpers import random_joke_generator

site = Blueprint('site', __name__, template_folder='site_templates')



@site.route('/')
def home():
    print("It's Magic time!")
    return render_template('index.html')

@site.route('/profile', methods = ['GET','POST'])
@login_required 
def profile():
    # random_joke_generator()
    my_bar = BarForm()

    try:
        if request.method == "POST" and my_bar.validate_on_submit():
            name = my_bar.name.data
            description = my_bar.description.data
            price = my_bar.price.data
            chocolate_quality = my_bar.chocolate_quality.data
            melt_temp = my_bar.melt_temp.data
            freeze_time = my_bar.freeze_time.data
            height = my_bar.height.data
            weight = my_bar.weight.data
            cost_of_production = my_bar.cost_of_production.data
            series = my_bar.series.data
            if my_bar.dad_joke.data:
                random_joke = my_bar.dad_joke.data
            else:
                random_joke = random_joke_generator()          
            user_token = current_user.token

            bar = Bar(name, description, price, chocolate_quality, melt_temp, freeze_time, height, weight, cost_of_production, series, random_joke, user_token)

            db.session.add(bar)
            db.session.commit()

            return redirect(url_for('site.profile'))
    except:
        raise Exception("Bar not created, please check your form and try again!")
    
    current_user_token = current_user.token

    bars = Bar.query.filter_by(user_token=current_user_token)

    
    return render_template('profile.html', form=my_bar, bars = bars )

bar_inventory/templates/bar_form.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="name-field">
            {{ form.name.label }}            
            {{ form.name(class = "form-control", placeholder="Name") }}
        </fieldset>
        <fieldset id="description-field">
            {{ form.description.label }}            
            {{ form.description(class = "form-control", placeholder="Description") }}
        </fieldset>
        <fieldset id="price-field">
            {{ form.price.label }}            
            {{ form.price(class = "form-control", placeholder="Price") }}
        </fieldset>
        <fieldset id="chocolate_quality">
            {{ form.chocolate_quality.label }}            
            {{ form.chocolate_quality(class = "form-control", placeholder="Chocolate Quality") }}
        </fieldset>
        <fieldset id="melt_temp">
            {{ form.melt_temp.label }}            
            {{ form.melt_temp(class = "form-control", placeholder="Melting Tempature") }}
        </fieldset>
        <fieldset id="freeze_time">
            {{ form.freeze_time.label }}            
            {{ form.freeze_time(class = "form-control", placeholder="Freeze Time") }}
        </fieldset>
        <fieldset id="height-field">
            {{ form.height.label }}            
            {{ form.height(class = "form-control", placeholder="Height") }}
        </fieldset>
        <fieldset id="weight-field">
            {{ form.weight.label }}            
            {{ form.weight(class = "form-control", placeholder="Weight") }}
        </fieldset>
        <fieldset id="cop-field">
            {{ form.cost_of_production.label }}            
            {{ form.cost_of_production(class = "form-control", placeholder="Cost of Production") }}
        </fieldset>
        <fieldset id="series-field">
            {{ form.series.label }}            
            {{ form.series(class = "form-control", placeholder="Series") }}
        </fieldset>
        <fieldset id="dadjoke-field">
            {{ form.dad_joke.label }}            
            {{ form.dad_joke(class = "form-control", placeholder="Dad Joke") }}
        </fieldset>


        <!-- Submit Button Area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2") }}

    </div>   
</form>

bar_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Candy Bar API</title>
</head>
<body>

    <!-- Nav Bar  -->
    <nav class="ct-nav">

        <div>
            <img src="../static/images/barlogo.png" alt="bar logo">
        </div>

        <div>
           <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Candy Bar Project</li>

                </a>
                <a href="{{ url_for('site.home') }}">
                    <li>Donate</li>

                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>

                </a>
                <a href="#">
                    <li>Log Out</li>

                </a>
                <a href="{{ url_for('auth.signin')  }}">
                    <li>Sign In</li>

                </a>
                <a href="{{ url_for('auth.signup')  }}">
                    <li>Sign Up</li>

                </a>
           </ul>
        </div>

    </nav>

    {% block content %}

    <!-- other content lives here  -->

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

bar_inventory/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Place Username Here... ") }}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here... ") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password Here... ") }}
        </fieldset>

        {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}

    </div>




</form>